title: dmitrytsepelev.dev
description: "A home for my blog posts"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dmitrytsepelev.dev"

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from

google_analytics: UA-221390545-1

remote_theme: "jekyll/minima"

collections:
  talks:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      section: "writing"
  - scope:
      path: ""
      type: "talks"
    values:
      layout: "talk"
      section: "talks"
  - scope:
      path: "tag"
      type: "pages"
    values:
      layout: "tagpage"
      section: "writing"
